export const courses = [
    {
        id: 1,
        name: "React for Beginners",
        description: "Learn the basics of React to build stunning applications.",
        price: "$19.99",
        detailsLink: "#/course/react-for-beginners",
        image: "https://via.placeholder.com/300x200?text=React+for+Beginners",
        instructorName: "John Doe",
        instructorAvatar: "https://via.placeholder.com/100?text=JD",
        createdDate: "2023-01-15",
    },
    {
        id: 2,
        name: "JavaScript Essentials",
        description: "Master the fundamentals of JavaScript programming.",
        price: "$14.99",
        detailsLink: "#/course/javascript-essentials",
        image: "https://via.placeholder.com/300x200?text=JavaScript+Essentials",
        instructorName: "Jane Smith",
        instructorAvatar: "https://via.placeholder.com/100?text=JS",
        createdDate: "2023-02-22",
    },
    {
        id: 3,
        name: "CSS for Developers",
        description: "Create visually appealing web designs using advanced CSS.",
        price: "$9.99",
        detailsLink: "#/course/css-for-developers",
        image: "https://via.placeholder.com/300x200?text=CSS+for+Developers",
        instructorName: "Tom Brown",
        instructorAvatar: "https://via.placeholder.com/100?text=TB",
        createdDate: "2023-03-10",
    },
    {
        id: 4,
        name: "Node.js Basics",
        description: "Build fast and scalable network applications with Node.js.",
        price: "$24.99",
        detailsLink: "#/course/nodejs-basics",
        image: "https://via.placeholder.com/300x200?text=Node.js+Basics",
        instructorName: "Sara Green",
        instructorAvatar: "https://via.placeholder.com/100?text=SG",
        createdDate: "2023-04-18",
    },
    {
        id: 5,
        name: "Python for Everyone",
        description: "Learn Python programming from scratch.",
        price: "$29.99",
        detailsLink: "#/course/python-for-everyone",
        image: "https://via.placeholder.com/300x200?text=Python+for+Everyone",
        instructorName: "Mike Ross",
        instructorAvatar: "https://via.placeholder.com/100?text=MR",
        createdDate: "2023-05-01",
    },
    {
        id: 6,
        name: "HTML Masterclass",
        description: "Build solid foundations in HTML for web development.",
        price: "$9.99",
        detailsLink: "#/course/html-masterclass",
        image: "https://via.placeholder.com/300x200?text=HTML+Masterclass",
        instructorName: "Emma White",
        instructorAvatar: "https://via.placeholder.com/100?text=EW",
        createdDate: "2023-06-12",
    },
];