export const courses = [
    {
        id: 1,
        name: "React for Beginners",
        description: "Learn the basics of React to build stunning applications.",
        price: "$19.99",
        detailsLink: "#/course/react-for-beginners",
        image: "https://via.placeholder.com/300x200?text=React+for+Beginners",
        instructorName: "John Doe",
        instructorAvatar: "https://via.placeholder.com/100?text=JD",
        createdDate: "2023-01-15",
    },
    {
        id: 2,
        name: "JavaScript Essentials",
        description: "Master the fundamentals of JavaScript programming.",
        price: "$14.99",
        detailsLink: "#/course/javascript-essentials",
        image: "https://via.placeholder.com/300x200?text=JavaScript+Essentials",
        instructorName: "Jane Smith",
        instructorAvatar: "https://via.placeholder.com/100?text=JS",
        createdDate: "2023-02-22",
    },
    {
        id: 3,
        name: "CSS for Developers",
        description: "Create visually appealing web designs using advanced CSS.",
        price: "$9.99",
        detailsLink: "#/course/css-for-developers",
        image: "https://via.placeholder.com/300x200?text=CSS+for+Developers",
        instructorName: "Tom Brown",
        instructorAvatar: "https://via.placeholder.com/100?text=TB",
        createdDate: "2023-03-10",
    },
    {
        id: 4,
        name: "Node.js Basics",
        description: "Build fast and scalable network applications with Node.js.",
        price: "$24.99",
        detailsLink: "#/course/nodejs-basics",
        image: "https://via.placeholder.com/300x200?text=Node.js+Basics",
        instructorName: "Sara Green",
        instructorAvatar: "https://via.placeholder.com/100?text=SG",
        createdDate: "2023-04-18",
    },
    {
        id: 5,
        name: "Python for Everyone",
        description: "Learn Python programming from scratch.",
        price: "$29.99",
        detailsLink: "#/course/python-for-everyone",
        image: "https://via.placeholder.com/300x200?text=Python+for+Everyone",
        instructorName: "Mike Ross",
        instructorAvatar: "https://via.placeholder.com/100?text=MR",
        createdDate: "2023-05-01",
    },
    {
        id: 6,
        name: "HTML Masterclass",
        description: "Build solid foundations in HTML for web development.",
        price: "$9.99",
        detailsLink: "#/course/html-masterclass",
        image: "https://via.placeholder.com/300x200?text=HTML+Masterclass",
        instructorName: "Emma White",
        instructorAvatar: "https://via.placeholder.com/100?text=EW",
        createdDate: "2023-06-12",
    },
    {
        id: 7,
        name: "Intro to TypeScript",
        description: "Upgrade your JavaScript skills with TypeScript.",
        price: "$19.99",
        detailsLink: "#/course/typescript-intro",
        image: "https://via.placeholder.com/300x200?text=Intro+to+TypeScript",
        instructorName: "Alice Brown",
        instructorAvatar: "https://via.placeholder.com/100?text=AB",
        createdDate: "2023-07-10",
    },
    {
        id: 8,
        name: "Responsive Web Design",
        description: "Design stunning websites that adapt to any device.",
        price: "$12.99",
        detailsLink: "#/course/responsive-web-design",
        image: "https://via.placeholder.com/300x200?text=Responsive+Web+Design",
        instructorName: "Bob Grey",
        instructorAvatar: "https://via.placeholder.com/100?text=BG",
        createdDate: "2023-08-21",
    },
    {
        id: 9,
        name: "Vue.js Fundamentals",
        description: "Get started with Vue.js for simple and interactive UIs.",
        price: "$16.99",
        detailsLink: "#/course/vuejs-fundamentals",
        image: "https://via.placeholder.com/300x200?text=Vue.js+Fundamentals",
        instructorName: "Charlie Red",
        instructorAvatar: "https://via.placeholder.com/100?text=CR",
        createdDate: "2023-01-01",
    },
    {
        id: 10,
        name: "Django for Web Development",
        description: "Learn to build secure and robust web applications.",
        price: "$27.99",
        detailsLink: "#/course/django-web-development",
        image: "https://via.placeholder.com/300x200?text=Django+for+Web+Development",
        instructorName: "Debbie Blue",
        instructorAvatar: "https://via.placeholder.com/100?text=DB",
        createdDate: "2023-09-15",
    },
    {
        id: 11,
        name: "SQL Mastery",
        description: "Manage and analyze data using SQL.",
        price: "$18.99",
        detailsLink: "#/course/sql-mastery",
        image: "https://via.placeholder.com/300x200?text=SQL+Mastery",
        instructorName: "Eve Black",
        instructorAvatar: "https://via.placeholder.com/100?text=EB",
        createdDate: "2023-03-23",
    },
    {
        id: 12,
        name: "REST API with Flask",
        description: "Develop RESTful APIs using Flask.",
        price: "$25.99",
        detailsLink: "#/course/flask-api",
        image: "https://via.placeholder.com/300x200?text=REST+API+with+Flask",
        instructorName: "Frank White",
        instructorAvatar: "https://via.placeholder.com/100?text=FW",
        createdDate: "2023-06-17",
    },
    {
        id: 13,
        name: "GraphQL Basics",
        description: "Master the GraphQL query language and APIs.",
        price: "$22.99",
        detailsLink: "#/course/graphql-basics",
        image: "https://via.placeholder.com/300x200?text=GraphQL+Basics",
        instructorName: "Gina Green",
        instructorAvatar: "https://via.placeholder.com/100?text=GG",
        createdDate: "2023-05-25",
    },
    {
        id: 14,
        name: "Tailwind CSS Design",
        description: "Quickly build modern designs with Tailwind CSS.",
        price: "$29.99",
        detailsLink: "#/course/tailwind-css",
        image: "https://via.placeholder.com/300x200?text=Tailwind+CSS+Design",
        instructorName: "Hank Yellow",
        instructorAvatar: "https://via.placeholder.com/100?text=HY",
        createdDate: "2023-04-07",
    },
    {
        id: 15,
        name: "Angular Full Course",
        description: "Become proficient in Angular for advanced applications.",
        price: "$32.99",
        detailsLink: "#/course/angular-course",
        image: "https://via.placeholder.com/300x200?text=Angular+Full+Course",
        instructorName: "Ian Red",
        instructorAvatar: "https://via.placeholder.com/100?text=IR",
        createdDate: "2023-08-30",
    },
    {
        id: 16,
        name: "AWS Fundamentals",
        description: "Master the essentials of AWS cloud computing.",
        price: "$33.99",
        detailsLink: "#/course/aws-fundamentals",
        image: "https://via.placeholder.com/300x200?text=AWS+Fundamentals",
        instructorName: "Jack Green",
        instructorAvatar: "https://via.placeholder.com/100?text=JG",
        createdDate: "2023-04-14",
    },
    {
        id: 17,
        name: "Kubernetes Essentials",
        description: "Learn to deploy and manage containerized applications.",
        price: "$40.99",
        detailsLink: "#/course/kubernetes-essentials",
        image: "https://via.placeholder.com/300x200?text=Kubernetes+Essentials",
        instructorName: "Kate Lime",
        instructorAvatar: "https://via.placeholder.com/100?text=KL",
        createdDate: "2023-05-30",
    },
    {
        id: 18,
        name: "DevOps Practices",
        description: "Implement CI/CD pipelines and DevOps workflows.",
        price: "$35.99",
        detailsLink: "#/course/devops-practices",
        image: "https://via.placeholder.com/300x200?text=DevOps+Practices",
        instructorName: "Leo Blue",
        instructorAvatar: "https://via.placeholder.com/100?text=LB",
        createdDate: "2023-01-18",
    },
    {
        id: 19,
        name: "Blockchain Basics",
        description: "Discover the technology behind cryptocurrencies.",
        price: "$45.99",
        detailsLink: "#/course/blockchain-basics",
        image: "https://via.placeholder.com/300x200?text=Blockchain+Basics",
        instructorName: "Mia Pink",
        instructorAvatar: "https://via.placeholder.com/100?text=MP",
        createdDate: "2023-02-14",
    },
    {
        id: 20,
        name: "Machine Learning Intro",
        description: "Start your journey into Machine Learning.",
        price: "$50.99",
        detailsLink: "#/course/machine-learning-intro",
        image: "https://via.placeholder.com/300x200?text=Machine+Learning+Intro",
        instructorName: "Ned Orange",
        instructorAvatar: "https://via.placeholder.com/100?text=NO",
        createdDate: "2023-12-29",
    },
    {
        id: 21,
        name: "Data Analysis with Python",
        description: "Master data analysis techniques using Python.",
        price: "$29.99",
        detailsLink: "#/course/data-analysis-with-python",
        image: "https://via.placeholder.com/300x200?text=Data+Analysis+with+Python",
        instructorName: "Olivia Violet",
        instructorAvatar: "https://via.placeholder.com/100?text=OV",
        createdDate: "2023-11-01",
    },
    {
        id: 22,
        name: "Advanced React Patterns",
        description: "Level up your React skills with advanced patterns.",
        price: "$39.99",
        detailsLink: "#/course/advanced-react-patterns",
        image: "https://via.placeholder.com/300x200?text=Advanced+React+Patterns",
        instructorName: "Peter Green",
        instructorAvatar: "https://via.placeholder.com/100?text=PG",
        createdDate: "2023-12-10",
    },
    {
        id: 23,
        name: "Docker Essentials",
        description: "Simplify application deployment with Docker.",
        price: "$28.99",
        detailsLink: "#/course/docker-essentials",
        image: "https://via.placeholder.com/300x200?text=Docker+Essentials",
        instructorName: "Emma Blue",
        instructorAvatar: "https://via.placeholder.com/100?text=EB",
        createdDate: "2023-09-19",
    },
    {
        id: 24,
        name: "PHP for Beginners",
        description: "Learn the basics of PHP for dynamic web development.",
        price: "$12.99",
        detailsLink: "#/course/php-for-beginners",
        image: "https://via.placeholder.com/300x200?text=PHP+for+Beginners",
        instructorName: "Frank Wood",
        instructorAvatar: "https://via.placeholder.com/100?text=FW",
        createdDate: "2023-10-05",
    },
    {
        id: 25,
        name: "Golang in Practice",
        description: "Develop fast and efficient applications with Go.",
        price: "$42.99",
        detailsLink: "#/course/golang-in-practice",
        image: "https://via.placeholder.com/300x200?text=Golang+in+Practice",
        instructorName: "Liam Yellow",
        instructorAvatar: "https://via.placeholder.com/100?text=LY",
        createdDate: "2023-03-06",
    },
    {
        id: 26,
        name: "Java Development Bootcamp",
        description: "Become a professional Java developer.",
        price: "$49.99",
        detailsLink: "#/course/java-development-bootcamp",
        image: "https://via.placeholder.com/300x200?text=Java+Development+Bootcamp",
        instructorName: "Sophia Red",
        instructorAvatar: "https://via.placeholder.com/100?text=SR",
        createdDate: "2023-07-01",
    },
    {
        id: 27,
        name: "UI/UX Design Principles",
        description: "Learn to design user-friendly and engaging interfaces.",
        price: "$34.99",
        detailsLink: "#/course/ui-ux-design-principles",
        image: "https://via.placeholder.com/300x200?text=UI+UX+Design+Principles",
        instructorName: "Lucas Black",
        instructorAvatar: "https://via.placeholder.com/100?text=LB",
        createdDate: "2023-02-08",
    },
    {
        id: 28,
        name: "Swift for iOS Development",
        description: "Build stunning apps with Apple's Swift language.",
        price: "$44.99",
        detailsLink: "#/course/swift-ios-development",
        image: "https://via.placeholder.com/300x200?text=Swift+for+iOS+Development",
        instructorName: "Zoe Pink",
        instructorAvatar: "https://via.placeholder.com/100?text=ZP",
        createdDate: "2023-11-20",
    },
    {
        id: 29,
        name: "Introduction to Rust",
        description: "Explore systems programming with Rust.",
        price: "$39.99",
        detailsLink: "#/course/introduction-to-rust",
        image: "https://via.placeholder.com/300x200?text=Introduction+to+Rust",
        instructorName: "Hannah Green",
        instructorAvatar: "https://via.placeholder.com/100?text=HG",
        createdDate: "2023-03-03",
    },
    {
        id: 30,
        name: "Augmented Reality Development",
        description: "Start your journey into Augmented Reality.",
        price: "$55.99",
        detailsLink: "#/course/augmented-reality-development",
        image: "https://via.placeholder.com/300x200?text=Augmented+Reality+Development",
        instructorName: "George White",
        instructorAvatar: "https://via.placeholder.com/100?text=GW",
        createdDate: "2023-09-12",
    },
    {
        id: 31,
        name: "SEO Essentials",
        description: "Learn how to drive traffic to your website with SEO.",
        price: "$24.99",
        detailsLink: "#/course/seo-essentials",
        image: "https://via.placeholder.com/300x200?text=SEO+Essentials",
        instructorName: "Bella Gold",
        instructorAvatar: "https://via.placeholder.com/100?text=BG",
        createdDate: "2023-05-15",
    },
    {
        id: 32,
        name: "GraphQL with Apollo",
        description: "Build modern GraphQL APIs with Apollo Server.",
        price: "$32.99",
        detailsLink: "#/course/graphql-with-apollo",
        image: "https://via.placeholder.com/300x200?text=GraphQL+with+Apollo",
        instructorName: "Lily Blue",
        instructorAvatar: "https://via.placeholder.com/100?text=LB",
        createdDate: "2023-06-25",
    },
    {
        id: 33,
        name: "Scala for Developers",
        description: "Write scalable and functional code with Scala.",
        price: "$45.99",
        detailsLink: "#/course/scala-for-developers",
        image: "https://via.placeholder.com/300x200?text=Scala+for+Developers",
        instructorName: "Evan Castle",
        instructorAvatar: "https://via.placeholder.com/100?text=EC",
        createdDate: "2023-02-14",
    },
    {
        id: 34,
        name: "Mobile App Design with Figma",
        description: "Create visually stunning mobile app designs with Figma.",
        price: "$18.99",
        detailsLink: "#/course/mobile-app-design",
        image: "https://via.placeholder.com/300x200?text=Mobile+App+Design+with+Figma",
        instructorName: "Nina Blue",
        instructorAvatar: "https://via.placeholder.com/100?text=NB",
        createdDate: "2023-08-10",
    },
    {
        id: 35,
        name: "Cybersecurity Essentials",
        description: "Protect systems from security threats and attacks.",
        price: "$48.99",
        detailsLink: "#/course/cybersecurity-essentials",
        image: "https://via.placeholder.com/300x200?text=Cybersecurity+Essentials",
        instructorName: "Oliver White",
        instructorAvatar: "https://via.placeholder.com/100?text=OW",
        createdDate: "2023-01-13",
    },
    {
        id: 36,
        name: "Advanced Machine Learning",
        description: "Dive deeper into advanced machine learning concepts.",
        price: "$65.99",
        detailsLink: "#/course/advanced-machine-learning",
        image: "https://via.placeholder.com/300x200?text=Advanced+Machine+Learning",
        instructorName: "Eve Brown",
        instructorAvatar: "https://via.placeholder.com/100?text=EB",
        createdDate: "2023-12-19",
    },
    {
        id: 37,
        name: "Game Development with Unity",
        description: "Start building 3D games with Unity Engine.",
        price: "$42.99",
        detailsLink: "#/course/game-development-unity",
        image: "https://via.placeholder.com/300x200?text=Game+Development+with+Unity",
        instructorName: "Victor Black",
        instructorAvatar: "https://via.placeholder.com/100?text=VB",
        createdDate: "2023-10-15",
    },
    {
        id: 38,
        name: "R for Data Science",
        description: "Leverage R for telling stories from data.",
        price: "$38.99",
        detailsLink: "#/course/r-for-data-science",
        image: "https://via.placeholder.com/300x200?text=R+for+Data+Science",
        instructorName: "Sophia Blue",
        instructorAvatar: "https://via.placeholder.com/100?text=SB",
        createdDate: "2023-05-08",
    },
    {
        id: 39,
        name: "Salesforce Administration",
        description: "Administer and customize Salesforce for any organization.",
        price: "$59.99",
        detailsLink: "#/course/salesforce-admin",
        image: "https://via.placeholder.com/300x200?text=Salesforce+Administration",
        instructorName: "Rebecca Yellow",
        instructorAvatar: "https://via.placeholder.com/100?text=RY",
        createdDate: "2023-09-23",
    },
    {
        id: 40,
        name: "Data Engineering on Azure",
        description: "Learn to build scalable data pipelines on Microsoft Azure.",
        price: "$54.99",
        detailsLink: "#/course/data-engineering-azure",
        image: "https://via.placeholder.com/300x200?text=Data+Engineering+on+Azure",
        instructorName: "Samuel Green",
        instructorAvatar: "https://via.placeholder.com/100?text=SG",
        createdDate: "2023-04-28",
    },
];
export const courses1=[]
export const MY_LEARNING_COURSES = [
    {
        id: 1,
        name: "React for Beginners",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/640px-JavaScript-logo.png"
    },
    {
        id: 2,
        name: "Advanced JavaScript",
        image: "https://cdn-icons-png.flaticon.com/512/732/732212.png"
    },
    {
        id: 3,
        name: "CSS Mastery",
        image: "https://cdn-icons-png.flaticon.com/512/732/732190.png"
    }
];
export const orders = [
    {
        id: 1,
        orderDate: "2023-09-21",
        totalPrice: "$34.98",
        cardNumber: "1234567812345678",
        courses: [
            {
                id: 1,
                name: "React for Beginners",
                description: "Learn the basics of React to build stunning applications.",
                price: "$19.99",
                detailsLink: "#/course/react-for-beginners",
                image: "https://via.placeholder.com/300x200?text=React+for+Beginners",
                instructorName: "John Doe",
            },
            {
                id: 2,
                name: "JavaScript Essentials",
                description: "Master the fundamentals of JavaScript programming.",
                price: "$14.99",
                detailsLink: "#/course/javascript-essentials",
                image: "https://via.placeholder.com/300x200?text=JavaScript+Essentials",
                instructorName: "Jane Smith",
            },
        ],
    },
    {
        id: 2,
        orderDate: "2023-08-15",
        totalPrice: "$9.99",
        cardNumber: "1234567812345678",
        courses: [
            {
                id: 3,
                name: "CSS for Developers",
                description: "Create visually appealing web designs using advanced CSS.",
                price: "$9.99",
                detailsLink: "#/course/css-for-developers",
                image: "https://via.placeholder.com/300x200?text=CSS+for+Developers",
                instructorName: "Tom Brown",
            },
        ],
    },
];